services:
  - type: web
    name: chord-finder-api
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: gunicorn guitarChordFinder:app
    plan: free